/* English editorial catalogue. Stable IDs preserve existing links and bookmarks. */
(() => {
  const data=[
    ['gunes','Sun','sun','yildizlar','G2 V · main-sequence star',
      'The star that powers the solar system. Hydrogen fusion in its core supplies the energy radiated by the photosphere.',
      [['Diameter','1.39 million','km'],['Effective temperature','5,772','K'],['Core temperature','15 million','K'],['Equatorial rotation','25','days']],
      'G2 describes its spectrum; luminosity class V identifies a main-sequence star.',
      'The textured disk shows an enhanced-colour solar map, not the colour an unaided observer would see. Surface granulation comes from convection.',
      'Where does the energy come from?','The proton–proton chain converts hydrogen into helium in the core. Energy travels outward through a radiative zone and a convective envelope.',
      'sun/facts/','Hydrogen and helium dominate. The core is helium-enriched by fusion; photospheric and core abundances differ.'],
    ['dunya','Earth','earth','gunes-sistemi','Terrestrial planet',
      'A rocky planet with liquid-water oceans, a nitrogen–oxygen atmosphere and an active geological cycle.',
      [['Equatorial diameter','12,756','km'],['Sidereal rotation','23.9','hours'],['Orbital period','365.25','days'],['Ocean coverage','71','% of surface']],
      'Clouds, ocean reflection and the thin atmospheric limb are separate layers in this view.',
      'Continents and oceans use a global colour map. The cloud and night-light layers are static composites, not current weather or live observations.',
      'What lies below the surface?','A silicate crust and mantle surround an iron-rich core. Convection in the liquid outer core sustains the geodynamo.',
      'earth/facts/','Silicate crust/mantle; iron–nickel core; water hydrosphere. Dry air is about 78% N₂, 21% O₂ and 0.93% Ar, with variable water vapour.'],
    ['ay','Moon','moon','gunes-sistemi','Differentiated rocky satellite',
      'Earth’s tidally locked companion preserves impact basins, ancient volcanic plains and a regolith weathered by space.',
      [['Diameter','3,476','km'],['Mean Earth distance','384,400','km'],['Orbital period','27.3','days'],['Phase cycle','29.5','days']],
      'The sidereal orbital period and the lunar phase cycle are different.',
      'Dark basaltic maria contrast with brighter, heavily cratered highlands. The lighting control changes the terminator, not the mapped terrain.',
      'Why do we see the same side?','Tidal evolution synchronized the Moon’s rotation with its orbit. Libration still lets us see a little more than half its surface over time.',
      'moon/facts/','Anorthositic highlands, basaltic maria and impact-generated regolith over a silicate interior and a small metallic core.'],
    ['mars','Mars','mars','gunes-sistemi','Terrestrial planet',
      'A cold, arid world with a thin atmosphere, enormous volcanoes and evidence of a wetter geological past.',
      [['Mean diameter','6,780','km'],['Rotation','24.6','hours'],['Orbital period','687','days'],['Moons','2','Phobos and Deimos']],
      'Iron-bearing minerals and oxidized dust contribute to its reddish appearance.',
      'The map combines broad albedo patterns and polar ice. Surface relief is not a measured displacement model.',
      'What is the atmosphere like?','The low-pressure atmosphere is dominated by CO₂. Seasonal CO₂ frost and water ice influence the polar caps; global dust storms can alter the visible surface contrast.',
      'mars/facts/','Basaltic crust, silicate mantle and an iron-rich core containing lighter elements. CO₂ dominates the atmosphere, with N₂ and Ar.'],
    ['jupiter','Jupiter','jupiter','gunes-sistemi','Gas giant',
      'The largest planet has a deep hydrogen–helium envelope, powerful zonal winds and long-lived atmospheric vortices.',
      [['Mean diameter','139,800','km'],['Rotation','9.9','hours'],['Orbital period','11.9','years'],['Mean Sun distance','778 million','km']],
      'The visible bands are atmospheric belts and zones, not a solid surface.',
      'A cloud-top map shows alternating bands and the Great Red Spot. It is a historical composite; storms do not evolve dynamically in this model.',
      'Is there a surface to land on?','There is no sharply defined solid surface beneath the clouds. Pressure rises continuously inward, and hydrogen becomes electrically conducting at depth.',
      'jupiter/jupiter-facts/','H₂ and He dominate. CH₄, NH₃ and H₂O are important trace species. The deep interior includes metallic hydrogen and a distribution of heavy elements.'],
    ['saturn','Saturn','saturn','gunes-sistemi','Gas giant',
      'A rapidly rotating gas giant surrounded by an extensive disk of icy ring particles.',
      [['Equatorial diameter','120,500','km'],['Rotation','10.7','hours'],['Orbital period','29.4','years'],['Mean Sun distance','1.43 billion','km']],
      'The rings consist of orbiting particles, not a single rigid sheet.',
      'Pale cloud bands, rotational flattening and an inclined ring system. Ring brightness and shadows are approximations.',
      'Why are the rings so thin?','Repeated collisions damp motion perpendicular to the ring plane. Orbital resonances and interactions with moons help structure the rings and gaps.',
      'saturn/facts/','H₂/He envelope with CH₄ and NH₃ traces; metallic hydrogen at depth and a heavy-element interior. Ring particles are predominantly water ice.'],
    ['notron-yildizi','Neutron star','neutron','yildizlar','Compact remnant · pulsar example',
      'The collapsed core of a massive star packs stellar mass into a body only tens of kilometres across.',
      [['Diameter scale','20–30','km'],['Support','Dense matter','equation of state'],['Origin','Core collapse','massive-star evolution'],['Example','Pulsar','periodic emission']],
      'Not every neutron star is visible as a pulsar.',
      'The beams and magnetic-field guides explain pulsar geometry. They are not a visible-light photograph or a predicted light curve.',
      'Why does a pulsar flash?','Emission tied to the magnetic poles sweeps through space as the star rotates. We detect pulses only when the beam crosses our line of sight.',
      'universe/stars/types/','A neutron-rich interior beneath a dense crust. The high-density equation of state remains uncertain; ordinary main-sequence spectral classes do not apply.'],
    ['kara-delik','Black hole','blackhole','derin-uzay','Accreting compact object',
      'A region of spacetime bounded by an event horizon, illustrated here with a luminous accretion disk.',
      [['Boundary','Event horizon','causal boundary'],['Emission','Accretion flow','hot plasma'],['Size scale','Mass-dependent','no universal diameter'],['Dark feature','Shadow','not the horizon itself']],
      'The visible shadow is larger than the event horizon and depends on photon trajectories.',
      'The warm disk, bright approaching side and bent far-side image illustrate accretion and relativistic optics.',
      'Where does the light come from?','Hot matter outside the horizon radiates as it accretes. Gravitational lensing redirects this light; relativistic Doppler effects make the two sides appear asymmetric.',
      'universe/black-holes/','This is an illustrative accretion model, not a general-relativistic ray tracer. Disk colour, inclination and brightness are not tied to a particular observed black hole.'],
    ['orion','Orion Nebula','nebula','derin-uzay','H II region · M42',
      'A nearby region of active star formation, illuminated and ionized by young massive stars in the Trapezium cluster.',
      [['Catalogue','M42','Messier 42'],['Distance','About 1,500','light-years'],['Constellation','Orion','night-sky direction'],['Central cluster','Trapezium','young massive stars']],
      'Glowing ionized gas and cold molecular material trace different physical environments.',
      'A schematic cloud of gas and embedded stars. Its colours and depth are illustrative, not a reconstruction of the measured nebula.',
      'How does a star form?','Dense gas may collapse when gravity overcomes pressure and other support. In the simplest thermal Jeans model, collapse is possible for M > M_J, with M_J proportional to T^(3/2)ρ^(−1/2).',
      'mission/hubble/science/explore-the-night-sky/hubble-messier-catalog/messier-42/','Ultraviolet radiation ionizes hydrogen. Dust absorbs and scatters light. Angular momentum J = Iω is redistributed through protostellar disks during collapse.'],
    ['samanyolu','Milky Way','galaxy','derin-uzay','Barred spiral galaxy',
      'Our home galaxy contains a stellar disk, a central bar and bulge, gas, dust and an extended dark-matter halo.',
      [['Stellar disk diameter','Over 100,000','light-years'],['Morphology','Barred spiral','disk and central bulge'],['Solar orbital period','About 240 million','years'],['Environment','Local Group','galaxy group']],
      'Turn on “Sun’s location” to find our approximate position in the Local Arm.',
      'A three-dimensional morphological model. The arm geometry is schematic; we cannot photograph the Milky Way from outside.',
      'Do spiral arms rotate like a wheel?','No. Stars and gas have differential orbital motion, and spiral structure is not a set of rigid spokes. The display rotation is an inspection aid.',
      'universe/galaxies/','The Sun lies in the Local (Orion) Arm, about 26,000 light-years from the Galactic centre. The marker is enlarged and its azimuth is illustrative.'],
    ['merkur','Mercury','mercury','gunes-sistemi','Terrestrial planet',
      'A dense, heavily cratered planet with an unusually large metallic core and almost no atmosphere.',
      [['Diameter','4,880','km'],['Orbital period','88','days'],['Sidereal rotation','58.6','days'],['Solar day','176','days']],
      'Mercury is in a 3:2 spin–orbit resonance.',
      'Impact basins and cratered plains dominate the grey surface. The lighting is adjustable and does not represent today’s illumination.',
      'Why is its solar day so long?','Mercury rotates three times during two orbits. Combined with its orbital motion, this makes one noon-to-noon cycle last two Mercury years.',
      'mercury/facts/','Iron-rich core with a silicate mantle and crust. A tenuous exosphere contains O, Na, H, He and K; it is not a substantial atmosphere.'],
    ['venus','Venus','venus','gunes-sistemi','Terrestrial planet',
      'A rocky planet hidden beneath bright clouds and a dense CO₂ atmosphere with an extreme greenhouse effect.',
      [['Diameter','12,104','km'],['Orbital period','225','days'],['Retrograde rotation','243','days'],['Surface temperature','About 465','°C']],
      'Visible light mostly reveals clouds, not the solid surface.',
      'This view shows the cloud envelope. Surface geology requires radar or infrared observations; the cloud pattern is an illustrative map.',
      'Why is Venus hotter than Mercury?','Its massive CO₂ atmosphere strongly restricts the escape of thermal radiation. Distance from the Sun alone does not determine surface temperature.',
      'venus/venus-facts/','Silicate crust and mantle with a metallic core. The atmosphere is about 96.5% CO₂ and 3.5% N₂; clouds contain sulfuric-acid droplets.'],
    ['uranus','Uranus','uranus','gunes-sistemi','Ice giant',
      'A pale cyan planet whose extreme axial tilt produces unusually long and intense seasonal changes.',
      [['Equatorial diameter','51,118','km'],['Orbital period','84','years'],['Rotation','About 17','hours'],['Obliquity','About 98','degrees']],
      '“Ice giant” describes composition, not a solid frozen surface.',
      'Weak cloud-band contrast is intentional: Uranus is often relatively featureless in visible light. Rings are not included in this view.',
      'What makes it an ice giant?','Compared with Jupiter and Saturn, a larger fraction of its mass consists of elements heavier than hydrogen and helium. Interior layer boundaries and material phases remain model-dependent.',
      'uranus/facts/','An H₂/He atmosphere containing CH₄ overlies an interior enriched in water-, ammonia- and methane-related compounds and rock. Their exact proportions are uncertain.'],
    ['neptun','Neptune','neptune','gunes-sistemi','Ice giant',
      'A cold outer planet with an internally powered atmosphere, fast winds and transient dark vortices.',
      [['Equatorial diameter','49,528','km'],['Orbital period','165','years'],['Rotation','About 16','hours'],['Mean Sun distance','4.5 billion','km']],
      'Widely reproduced deep-blue images often exaggerate its true visible-light colour.',
      'The texture is colour-adjusted for a less saturated blue-green appearance. It remains a display map, not calibrated spectrophotometry.',
      'Why is methane important?','Methane preferentially absorbs red light and affects the planet’s visible colour. Aerosols, clouds and illumination also influence the observed spectrum.',
      'neptune/neptune-facts/','H₂/He atmosphere with CH₄. Interior models contain heavy elements, rock and volatile compounds under high pressure; there is no directly observed solid surface.'],
    ['pluton','Pluto','pluto','gunes-sistemi','Kuiper-belt dwarf planet',
      'A small world with volatile ices, rugged water-ice terrain and a seasonally changing atmosphere.',
      [['Diameter','2,377','km'],['Orbital period','248','years'],['Rotation','6.4','days'],['Region','Kuiper belt','outer solar system']],
      'Sputnik Planitia is a basin filled with nitrogen-rich ice.',
      'The New Horizons colour mosaic has uneven resolution and incomplete southern coverage. The smooth southern fill is a visual completion, not measured terrain.',
      'Why is the surface so varied?','Nitrogen, methane and carbon-monoxide ices can migrate or flow under Pluto’s changing seasonal conditions, while water ice behaves as a strong bedrock material.',
      'dwarf-planets/pluto/facts/','Rock and water ice in the interior; N₂, CH₄ and CO ices at the surface. The tenuous atmosphere is mainly nitrogen.'],
    ['ceres','Ceres','ceres','gunes-sistemi','Main-belt dwarf planet',
      'The largest object in the asteroid belt records a history involving water, hydrated minerals and brines.',
      [['Diameter','About 940','km'],['Orbital period','4.6','years'],['Rotation','9','hours'],['Region','Main asteroid belt','between Mars and Jupiter']],
      'Bright deposits in Occator crater are associated with salts.',
      'A Dawn Framing Camera global mosaic published by USGS replaces the procedural crater pattern. The display image has uneven polar coverage and baked-in illumination. Its spherical wrapping is for visual inspection, not precise cartography or measured relief.',
      'What do the bright spots tell us?','Salt-rich material points to water-related processes in the interior. The bright faculae are compositionally distinct from the surrounding dark surface.',
      'dwarf-planets/ceres/facts/','Hydrated silicates, carbonates, other salts and water ice. Interior differentiation and past brine activity influence the surface geology.'],
    ['europa','Europa','europa','gunes-sistemi','Icy Galilean moon',
      'Jupiter’s fractured ice moon is a major candidate for a subsurface ocean in contact with a rocky interior.',
      [['Diameter','3,122','km'],['Orbital period','3.55','days'],['Primary','Jupiter','gas giant'],['Surface','Water ice','fractured shell']],
      'Tidal deformation provides an important source of internal energy.',
      'A NASA 3D Resources texture shows the fractured ice and dark lineae. This grayscale visualization map is not a calibrated natural-colour image or a terrain model.',
      'How can an ocean remain liquid?','Tidal dissipation and internal heat can help maintain liquid water below an insulating ice shell. Shell thickness and ocean properties remain uncertain.',
      'jupiter/moons/europa/','Water-ice shell, likely saline ocean, silicate mantle and metallic core. Surface contaminants affect colour and may include salts.'],
    ['titan','Titan','titan','gunes-sistemi','Atmosphere-bearing icy moon',
      'Saturn’s largest moon has a dense atmosphere, organic haze and a methane-based weather cycle.',
      [['Diameter','5,150','km'],['Orbital period','15.9','days'],['Primary','Saturn','gas giant'],['Atmosphere','Mostly N₂','with methane']],
      'Titan’s orange haze hides most surface detail in visible light.',
      'A low-contrast orange haze envelope with a faint bluish atmospheric limb, inspired by Cassini natural-colour observations. Surface lakes are hidden at visible wavelengths. This is an atmospheric illustration, not a calibrated scattering calculation.',
      'What fills the lakes?','Methane and ethane form surface liquids in Titan’s cold environment. Water ice instead acts as rock, while a water-rich ocean may exist deeper inside.',
      'saturn/moons/titan/facts/','Nitrogen-rich atmosphere, CH₄ and organic aerosols; water-ice crust and hydrocarbon lakes, with a possible subsurface water ocean.'],
    ['enceladus','Enceladus','enceladus','gunes-sistemi','Ocean-bearing icy moon',
      'A small, reflective moon whose south-polar plumes connect its subsurface ocean to space.',
      [['Diameter','504','km'],['Orbital period','1.37','days'],['Primary','Saturn','gas giant'],['Outer shell','Water ice','over a global ocean']],
      'Cassini sampled material emitted from the south-polar region.',
      'A NASA 3D Resources texture shows fractures and cratered terrain. Coverage and detail vary across this visualization map; the geometry remains spherical and does not reconstruct plume activity.',
      'What escapes through the fractures?','Water vapour and ice grains carry salts and organic compounds from the interior. Tidal heating helps sustain geological activity.',
      'saturn/moons/enceladus/','Water-ice shell, saline global ocean and rocky interior. Plume grains contain salts and organic compounds.'],
    ['bennu','Bennu','bennu','gunes-sistemi','Carbon-rich rubble-pile asteroid',
      'A small near-Earth asteroid assembled from loosely bound fragments, with an equatorial ridge and a boulder-covered surface.',
      [['Width','About 500','m'],['Rotation','4.3','hours'],['Population','Near-Earth','asteroid'],['Sample return','2023','OSIRIS-REx']],
      'Its low gravity allows a loose aggregate structure rather than a single solid rock.',
      'A NASA-distributed visualization mesh, shaded in neutral grey. This is not a phototextured OSIRIS-REx terrain product; display exposure is increased.',
      'Why return a sample?','Laboratory analysis can identify mineral and organic chemistry at resolutions unavailable from remote sensing, while preserving the geological context supplied by spacecraft observations.',
      'solar-system/asteroids/101955-bennu/','Carbon-rich material, hydrated minerals and organic compounds. The dark regolith and boulders have a low geometric albedo.'],
    ['67p','67P / Churyumov–Gerasimenko','comet','gunes-sistemi','Jupiter-family comet',
      'Rosetta’s target has two irregular lobes joined by a narrow neck. Sublimating volatiles drive its activity near the Sun.',
      [['Size scale','A few','km'],['Orbital period','6.45','years'],['Rotation','About 12.4','hours'],['Spacecraft','Rosetta','ESA']],
      'The nucleus is extremely dark; display exposure is increased to reveal its shape.',
      'A continuous, smoothed approximation of the flattened lobes and neck, informed by Rosetta morphology. This is not the SHAP5 mission mesh. Extended tails are omitted at this close-up scale.',
      'Why are comet tails different?','Dust responds to radiation pressure and orbital motion, while ionized gas couples to the solar wind. Neither tail is a rigid structure attached to the rotating nucleus.',
      'solar-system/comets/67p-churyumov-gerasimenko/','Dust, organic-rich material and volatile ices including H₂O, CO₂ and CO. Activity depends on illumination, thermal history and volatile availability.'],
    ['kirmizi-dev','Red giant','redgiant','yildizlar','Red giant branch · RGB example',
      'An expanded star with a cool photosphere and a high luminosity, shown here as a generic low- or intermediate-mass RGB star.',
      [['Evolution','RGB','post-main-sequence'],['Core','Inert helium','in this example'],['Fusion','Hydrogen shell','around the core'],['H–R location','Upper right','cool and luminous']],
      'A lower surface temperature does not imply a lower total luminosity.',
      'Large convection cells are an illustrative surface treatment. This is not an image of a specific star.',
      'Why can a cool star be luminous?','Luminosity depends on both radius and temperature: L = 4πR²σT_eff⁴. The large emitting area of a giant can outweigh its lower effective temperature.',
      'universe/stars/types/','An inert helium core, hydrogen-burning shell and expanded envelope in this RGB example. No single spectral subtype applies to every red giant.'],
    ['beyaz-cuce','White dwarf','whitedwarf','yildizlar','Electron-degenerate stellar remnant',
      'A compact remnant, typically roughly Earth-sized, that cools by radiating stored thermal energy.',
      [['Radius scale','Earth-like','compact remnant'],['Support','Electron degeneracy','quantum pressure'],['Power source','Stored heat','cooling'],['Evolution','Stellar remnant','not main sequence']],
      'DA and DB describe atmospheric spectra, not interchangeable names for all white dwarfs.',
      'A hot, compact luminous sphere. Its size is enlarged for inspection and does not share a scale with the other stars.',
      'What supports the star?','Electron degeneracy pressure supports a typical white dwarf. It does not require ongoing core fusion; its luminosity decreases as it cools.',
      'universe/stars/types/','Commonly a carbon–oxygen interior with a thin H/He envelope. DA spectra show hydrogen; DB spectra show helium. This generic example has no assigned subtype.'],
    ['andromeda','Andromeda Galaxy','andromeda','derin-uzay','Spiral galaxy · M31',
      'The nearest large spiral galaxy to the Milky Way, seen across the Local Group at a distance of about 2.5 million light-years.',
      [['Distance','2.5 million','light-years'],['Catalogue','M31','Messier 31'],['Morphology','Spiral','disk galaxy'],['Constellation','Andromeda','night-sky direction']],
      'A bright central bulge is surrounded by a stellar disk and dust-rich structure.',
      'A schematic three-dimensional disk. Rotating it changes the viewing angle, not the actual orientation of M31 on today’s sky.',
      'Why does it look elongated?','Its disk is strongly inclined to our line of sight. Changing the model’s orientation helps separate intrinsic structure from projection effects.',
      'mission/hubble/science/explore-the-night-sky/hubble-messier-catalog/messier-31/','An older stellar bulge, a star-forming disk, gas, dust and an extended halo. Individual displayed points represent populations, not a measured star catalogue.']
  ];
  window.AstroCatalog=data.map(([id,name,kind,category,type,intro,facts,highlight,appearance,question,explanation,path,composition])=>({
    id,name,kind,category,type,intro,facts,highlight,appearance,question,explanation,
    group:category==='yildizlar'?'Stars':category==='derin-uzay'?'Deep space':'Solar system',
    subtitle:type,sceneLabel:type,source:'https://science.nasa.gov/'+path,
    technical:[['Composition and structure',composition]],
    modelNote:appearance+' Objects are not shown at a common scale. Rotation and lighting are for inspection, not an ephemeris.'
  }));
  const orbits={merkur:[.38709927,.20563593,7.00497902,252.25032350,77.45779628,48.33076593],venus:[.72333566,.00677672,3.39467605,181.97909950,131.60246718,76.67984255],dunya:[1.00000261,.01671123,-.00001531,100.46457166,102.93768193,0],mars:[1.52371034,.09339410,1.84969142,-4.55343205,-23.94362959,49.55953891],jupiter:[5.202887,.04838624,1.30439695,34.39644051,14.72847983,100.47390909],saturn:[9.53667594,.05386179,2.48599187,49.95424423,92.59887831,113.66242448],uranus:[19.18916464,.04725744,.77263783,313.23810451,170.95427630,74.01692503],neptun:[30.06992276,.00859048,1.77004347,-55.12002969,44.96476227,131.78422574]};
  for(const o of window.AstroCatalog){
    if(orbits[o.id]){const [a,e,i,L,peri,node]=orbits[o.id],wrap=x=>(x%360+360)%360;
      o.orbit=[['a · semi-major axis',a,'au'],['e · eccentricity',e,'dimensionless'],['i · inclination',i,'°'],['Ω · longitude of ascending node',node,'°'],['ω · argument of perihelion',wrap(peri-node),'°'],['M₀ · mean anomaly at epoch',wrap(L-peri),'°']];
      o.orbitNote='Epoch J2000.0; heliocentric, mean J2000 ecliptic and equinox. JPL fitted elements for 1800–2050, not current osculating elements.'+(o.id==='dunya'?' Earth data refer to the Earth–Moon barycentre; the tiny negative inclination is a signed fit parameter.':'');
    }
    if(o.category==='yildizlar')o.technical.push(['Luminosity and flux','L is total radiated power in watts. For an isotropic source without extinction, F = L/(4πd²), in W/m². Apparent brightness also depends on distance and extinction.']);
  }
})();
